# Form implementation generated from reading ui file 'c:\Users\User\OneDrive\Escritorio\Proyecto_Banco\app\gui\main.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_main(object):
    def setupUi(self, main):
        main.setObjectName("main")
        main.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=main)
        self.centralwidget.setObjectName("centralwidget")
        main.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=main)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuArchivo = QtWidgets.QMenu(parent=self.menubar)
        self.menuArchivo.setObjectName("menuArchivo")
        self.menuCr_ditos = QtWidgets.QMenu(parent=self.menubar)
        self.menuCr_ditos.setObjectName("menuCr_ditos")
        main.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=main)
        self.statusbar.setObjectName("statusbar")
        main.setStatusBar(self.statusbar)
        self.actionDesarrolladores = QtGui.QAction(parent=main)
        self.actionDesarrolladores.setObjectName("actionDesarrolladores")
        self.btnRegistrar_transferencia = QtGui.QAction(parent=main)
        self.btnRegistrar_transferencia.setObjectName("btnRegistrar_transferencia")
        self.btnReportar_transferencia = QtGui.QAction(parent=main)
        self.btnReportar_transferencia.setObjectName("btnReportar_transferencia")
        self.btnHistorial_de_transferencias = QtGui.QAction(parent=main)
        self.btnHistorial_de_transferencias.setObjectName("btnHistorial_de_transferencias")
        self.menuArchivo.addAction(self.btnRegistrar_transferencia)
        self.menuArchivo.addAction(self.btnReportar_transferencia)
        self.menuArchivo.addAction(self.btnHistorial_de_transferencias)
        self.menuCr_ditos.addAction(self.actionDesarrolladores)
        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menubar.addAction(self.menuCr_ditos.menuAction())

        self.retranslateUi(main)
        QtCore.QMetaObject.connectSlotsByName(main)

    def retranslateUi(self, main):
        _translate = QtCore.QCoreApplication.translate
        main.setWindowTitle(_translate("main", "Banco Santa Fe - Transferencias"))
        self.menuArchivo.setTitle(_translate("main", "Archivo"))
        self.menuCr_ditos.setTitle(_translate("main", "Créditos"))
        self.actionDesarrolladores.setText(_translate("main", "Desarrolladores"))
        self.btnRegistrar_transferencia.setText(_translate("main", "Registrar transferencia"))
        self.btnRegistrar_transferencia.setShortcut(_translate("main", "Ctrl+R"))
        self.btnReportar_transferencia.setText(_translate("main", "Reportar transferencia"))
        self.btnReportar_transferencia.setShortcut(_translate("main", "Ctrl+T"))
        self.btnHistorial_de_transferencias.setText(_translate("main", "Historial de transferencias"))
        self.btnHistorial_de_transferencias.setShortcut(_translate("main", "Ctrl+J"))
